# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Timestamp of this statement')),
                ('source', models.TextField(help_text='Source of the statement')),
                ('claim', models.TextField(help_text='Text of the claim')),
                ('judgement', models.TextField(help_text='Politifact judgement')),
                ('summary', models.TextField(help_text='Explanation')),
                ('url', models.TextField(help_text='Link to politifact page')),
            ],
        ),
    ]
